name: Continuous Delivery to Google Cloud Registry 

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: eu.gcr.io
  IMAGE: welcome-page

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Gcloud
        run: |
          gcloud auth configure-docker -q

      - name: Build
        run: |-
          docker build \
          --tag "$GAR_LOCATION/$PROJECT_ID/$IMAGE" . \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \

      - name: Publish
        run: |-
          docker push "$GAR_LOCATION/$PROJECT_ID/$IMAGE"
